scheduling/twitter-info-poc/config/routes.rb
TwitterInfoPoc::Application.routes.draw do
  resources :user_followers do
    get :followers, on: :member
  end

  root to: "home#index"

  match "auth/twitter/callback" => "sessions#create"
  delete "session" => "sessions#destroy", as: "delete_session"
end

scheduling/twitter-info-poc/app/models/api_timeout.rb
class ApiTimeout < ActiveRecord::Base
  attr_accessible :api, :reset_time
end

scheduling/twitter-info-poc/app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :avator_url, :description, :location, :name, :real_name

  has_many :user_followers_contacts
  has_many :user_followers, through: :user_followers_contacts

  def self.for_uid(uid)
    where(uid: uid).first_or_create
  end

  def from_twitter(attrs)
    self.name = attrs[:screen_name]
    self.location = attrs[:location]
    self.avator_url = attrs[:profile_image_url]
    self.real_name = attrs[:name]
    self.description = attrs[:description]
    self.followers_count = attrs[:followers_count]
    self.last_update = Time.now
  end
end

scheduling/twitter-info-poc/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :oauth_secret, :oauth_token, :uid
  has_many :user_followers

  def self.from_omniauth(auth)
    user = find_or_create_by_uid(auth["uid"])
    user.oauth_token = auth["credentials"]["token"]
    user.oauth_secret = auth["credentials"]["secret"]
    user.name = auth["credentials"]["name"]
    user.save!
    Contact.for_uid(auth["uid"])
    user
  end
end

scheduling/twitter-info-poc/app/models/user_follower.rb
class UserFollower < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  has_many :user_followers_contacts
  has_many :contacts, through: :user_followers_contacts
  
  has_one :contact, foreign_key: :uid, primary_key: "twitter_id"

  def self.for_user(uid)
    where(user_id: uid)
  end

  after_create do
    Contact.for_uid(self.twitter_id)
  end
end

scheduling/twitter-info-poc/app/models/user_followers_contact.rb
class UserFollowersContact < ActiveRecord::Base
  belongs_to :user_follower
  belongs_to :contact
end

scheduling/twitter-info-poc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout "application"
  helper_method :logged_in?, :current_user

  protected
  
  def logged_in?
    !!current_user_id
  end

  def current_user
    @current_user ||= load_user(current_user_id)
  end

  def current_user=(user)
    session[:current_user_id] = user.try(:id)
  end

  def current_user_id
    session[:current_user_id]
  end

  def load_user(id)
    id ? User.find(id) : nil
  end

  def login_required
    unless logged_in?
      flash[:error] = "Login required"
      redirect_to root_path
    end
  end
end

scheduling/twitter-info-poc/app/controllers/home_controller.rb
class HomeController < ApplicationController  
  def index
    
  end
end

scheduling/twitter-info-poc/app/controllers/user_followers_controller.rb
class UserFollowersController < ApplicationController
  before_filter :login_required
  
  # POST /user_followers
  # POST /user_followers.json
  def create
    @user_follower = UserFollower.new(user_follower_params)
    @user_follower.user_id = current_user_id

    respond_to do |format|
      if @user_follower.save
        format.html { redirect_to root_path }
        format.json { render json: @user_follower, status: :created, location: @user_follower }
      else
        format.html { render action: "new" }
        format.json { render json: @user_follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_followers/1
  # DELETE /user_followers/1.json
  def destroy
    @user_follower = UserFollower.for_user(current_user_id).find(params[:id])
    @user_follower.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  def followers
    @user_follower = UserFollower.for_user(current_user_id).find(params[:id])
    @followers = UserFollowersContact.where(user_follower_id: @user_follower.id).
      preload(:contact).
      page(params[:page])
  end
  
  protected

  def user_follower_params
    params.require(:user_follower).permit(:twitter_id)
  end
end

scheduling/twitter-info-poc/app/helpers/user_followers_helper.rb
module UserFollowersHelper
end

scheduling/twitter-info-poc/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TwitterInfoPoc"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") TwitterInfoPoc
          .container.nav-collapse
            %ul.nav
              - if logged_in?
                %li= link_to "Sign out", delete_session_path, method: :delete

    .container

      .content
        .row
          .span9
            = flash_block
            = yield
          - if logged_in?
            = render partial: "/layouts/partials/sidebar"
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

scheduling/twitter-info-poc/app/views/layouts/partials/_sidebar.html.haml
.span3
  .well.sidebar-nav
    %h3 Sidebar
    %ul.nav.nav-list
      %li.nav-header Sidebar
      %li= link_to "Link 1", "/path1"
      %li= link_to "Link 2", "/path2"
      %li= link_to "Link 3", "/path3"